#!/usr/bin/env bash
### pool-update -- update pool metadata
## Usage: pool update <root>

[[ $(pool check-registry $1) == "up to date" ]] && echo "up to date" && exit

LIVE=true
POOL_METADATA="$BASE_DIR/pools/$NETWORK/metadata/$1.json"
POOL_SLUG="\"$(cat $POOL_METADATA | jq -r ".slug")\""
METADATA_HASH="\"$(pool pin-file $POOL_METADATA)\""

seth send $(pool --registry-address) 'file(address, bool, string, string)' $1 $LIVE $POOL_SLUG $METADATA_HASH
